name: sixam_mart
description: A Multi-vendor Food. Grocery, eCommerce, Pharmacy & Parcel service.
publish_to: 'none' #
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6
  firebase_core: 
  firebase_messaging: 
  flutter_local_notifications: ^9.5.3+1
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pin_code_fields: ^7.3.0
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.3.2
  flutter_typeahead: ^4.0.0
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.5+3
  image_picker_ios: ^0.8.5+6
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  flutter_inappwebview: ^5.4.3+7
  flutter_widget_from_html: ^0.8.5
  fwfh_selectable_text: ^0.8.3+1
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.1.2
  http: ^0.13.4
  pointer_interceptor: ^0.9.0+1
  phone_number: ^0.12.0+1
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.1
#  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.7
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.2
  dotted_border: ^2.0.0+1
  share_plus: ^4.0.10
  fwfh_text_style: ^2.22.8+1
  expandable_bottom_sheet: ^1.1.1+1
  video_player: ^2.4.7
  chewie: ^1.4.0
  shrink_sidemenu: ^2.0.0+2-null-safety

  #social app
  flutter_datetime_picker: ^1.4.0
  intl:
  image_cropper: ^1.5.1
  dio: ^4.0.6
  async: ^2.4.1
  toast: ^0.3.0
  flutter_absolute_path: 
    git:
      url: https://github.com/canewsin/flutter_absolute_path.git
  path: ^1.7.0
  custom_refresh_indicator: ^1.2.1
  flutter_screenutil: ^5.5.3+2
  flutter_slidable: ^2.0.0
  giphy_get: ^2.0.4
  timeago: ^3.2.2
  inview_notifier_list: ^3.0.0
  permission_handler: ^10.0.0
  screenshot:
  dashed_circle: ^0.0.1
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  photofilters: ^3.0.1
  flutter_spinkit: ^5.1.0
  cloud_firestore: any
  firebase_auth: 4.2.3
  firebase_database: 
  firebase_storage: 
  convex_bottom_bar: ^3.0.0
  another_flushbar: ^1.10.20
  google_sign_in: ^5.4.0
  csc_picker: ^0.2.5
  flutter_image_compress: ^1.1.0
  linkable: ^3.0.1
  flutter_staggered_grid_view: ^0.4.0
  webview_flutter: ^3.0.4
  visibility_detector: ^0.3.3
  video_thumbnail:
    git: https://github.com/ajbcoder/video_thumbnail
  video_compress: ^3.0.0
  dynamic_themes:
  iconly: ^1.0.1
  # nb_utils: ^4.6.16
  nb_utils: ^5.0.6
  flutter_svg: ^1.1.1+1
  line_awesome_flutter: ^2.0.0
  adaptive_theme: ^3.1.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  ionicons: ^0.1.2
  share: ^2.0.4
  flutter_reaction_button: ^2.0.0+1
  google_mobile_ads: ^2.0.1
  filesize: ^2.0.1
  file_picker: ^4.6.1
  flutter_pdfview: ^1.2.2
  geocoding: ^2.0.4
  collection: ^1.15.0-nullsafety.4
  card_swiper: ^2.0.4
  path_provider_android: ^2.0.21 
  connectivity_plus_web:
  font_awesome_flutter: ^10.3.0
  dotted_line: ^3.1.0
  flutter_expandable_fab: ^1.7.1

  #service provider app
  # COMMON
  html: ^0.15.2

  # FIREBASE
  firebase_crashlytics: ^3.0.17
  firebase_remote_config: ^3.0.15

  # PUSH NOTIFICATION
  onesignal_flutter: 3.4.1

  # STATE MANAGEMENT
  # mobx: 1.2.1+4
  # flutter_mobx: 1.1.0+2
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5

  # ICON
  flutter_vector_icons: ^2.0.0

  # IMAGE
  lottie: ^2.3.0

  # OTHER
  country_picker: 2.0.19
  flutter_custom_tabs: ^1.0.4
  firebase_pagination: ^3.0.0

  # SOCIAL LOGIN
  the_apple_sign_in: ^1.1.1

  # PAYMENT GATEWAYS
  razorpay_flutter: ^1.3.4
  flutterwave_standard: ^1.0.7
  # flutter_stripe: ^9.0.0+1
  cinetpay: ^1.0.6
  #  flutter_braintree: ^3.0.0 Remove due to play store does not approving the app
  
  game:
    path: 

dependency_overrides:
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.3.3
  # mobx_codegen: 1.1.2
  mobx_codegen: ^2.1.1
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/images/
    - assets/language/

    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images1/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900